### ISSUE TITLE
are the instructions complete?

### ISSUE THREAD

**Issue by stevemart** [IBM/serverless-language-translation#18]
I read through the README and this doesn't give me a lot of confidence that this is actually complete, see the screenshot:

<img width="887" alt="screen shot 2018-05-15 at 11 42 29 am" src="https://user-images.githubusercontent.com/4118756/40067859-2b5f404a-5835-11e8-970e-03cd33ef2317.png">

It would also be great to have a screenshot of the app running or the serverless-translation-ui

**Comment by markstur** [comment]
Does not look complete to me.  I can fix some of it.

**Comment by kkbankol-ibm** [comment]
@stevemart yes, there's definitely still a bit more work to be done. It looks like the backend (actions, MQTT feed, etc) is mostly complete. I'm finishing up an install script with a Dockerfile so I can repeatedly test the install process out
The main pieces that we're missing are
- Test scripts, which are nearly complete for this repo and in the [mqttfeed](https://github.com/kkbankol-ibm/openwhisk-package-mqtt-watson) repo
- Our free ETCD service offering was removed, which we were using to keep track of Twilio subscribers. I'm testing out Redis as an alternative
- The Monitoring UI is mostly functional but needs a lot of cleanup

I have my changes pushed to the dev branch in this repo, and should be able to submit a PR tomorrow

**Comment by stevemart** [comment]
@kkbankol-ibm this is mostly complete too, i think https://github.com/IBM/serverless-language-translation/pull/27 has addressed this. Please look at the other open issues in the repo and go through them.
