### ISSUE TITLE
 Port all issues from [Taiga kanban](https://tree.taiga.io/project/kalonb91-lang/) to this repository

### ISSUE THREAD

**Issue by markstur** [IBM/serverless-language-translation#24]
Haven't vetted this either, but want it out of the README, so putting it in an issue.
Port all issues from [Taiga kanban](https://tree.taiga.io/project/kalonb91-lang/) to this repository

**Comment by kkbankol-ibm** [comment]
@ljbennett62 @markstur, I'd say the list of tasks in taiga (similar to trello) are mostly "nice to have" features, so I think this can be closed and we can gradually add those features in
