### ISSUE TITLE
mqqt-watson/feed-action issue

### ISSUE THREAD

**Issue by markstur** [IBM/serverless-language-translation#28]
The "wsk" CLI is not available. It is now "bx wsk".

* There is a PR to fix this in the krook repo.
* In the kkbankol-ibm fork, I can make it work using double quotes and "bx wsk" as the $CLI passed to the script.  But that should be documented or just be the default (like the PR).

I can't raise any issues in the kkbankol-ibm fork and it might be out-of-sync with the krook version.  So I guess I'll raise the issue here, but that's confusing.

**Comment by markstur** [comment]
Also that "submodule" readme uses translateText in the example, but it doesn't exist yet. So it would be better not to have folks try to follow that.

**Comment by kkbankol-ibm** [comment]
fixed
