### ISSUE TITLE
Microphone & Speaker

### ISSUE THREAD

**Issue by zmohammad01** [IBM/serverless-language-translation#29]
The button for microphone does not seem to work and the speaker only works on the first chat window.

**Comment by loafyloaf** [comment]
I am not having any problems getting the button for the microphone to work for the first chat window.  If you are experiencing otherwise, some screenshots / small video might help in troubleshooting.  This would be, I believe, a design decision that makes sense, as one person would only be speaking or needing to hear one language at a time.  While the app can show more than one chat window at a time, so you can see it in action, you can't really listen to more than one translation at a time.
@kkbankol-ibm what do you think?

**Comment by zmohammad01** [comment]
Does the browser I am using matter? I was using Chrome and experienced the issue of the buttons being clickable, but no recording or sound was produced. 

If it is a browser related issue, can there be a suggestion added that it works with “x” browser. 

Regards,
Zia Mohammad

**Comment by kkbankol-ibm** [comment]
Hey @zmohammad01, yes, it looks like Chrome disables microphone access for http hosts but not https according to their security policy...Deploying on IBM Cloud allows access via both http and https, so prepending an "https" at the beginning of the url should work like so.

[https://translation-mqtt.mybluemix.net/](https://translation-mqtt.mybluemix.net/)

**Comment by zmohammad01** [comment]
I just tried that link, but it does not seem to work. The link will open
up, but I will not be able to open up another chat window or be able to
send any text to the chat window. Things work find without the https.

Cheers,
Zia K. Mohammad
Product Manager - IBM Watson Natural Language APIs
http://www.linkedin.com/in/ziamohammad

**Comment by zmohammad01** [comment]
Cool, so I was able to get it to load with the https! Mic and speaker
seemed to work for the first chat box, but not for any of the others.

Additionally, I wasn't able to input any text into the other chat windows
or get the mic/speaker to work on those.


Cheers,
Zia K. Mohammad

**Comment by zmohammad01** [comment]
Thanks much for the update, looking forward to hearing back. (On a side note we just updated the API to v3 so that might help in translation quality)

Regards,
Zia Mohammad

**Comment by zmohammad01** [comment]
Awesome thanks. Let me know when it’s updated! Looking forward to trying it out. (The v3 might give more languages too that can be in the dropdown)

Regards,
Zia Mohammad

**Comment by kkbankol-ibm** [comment]
@ljbennett62 the original issue here (mic and speaker) has been addressed, and I've just upgraded the translate action to use V3 of the translation service as Zia suggested

**Comment by zmohammad01** [comment]
🎉 

Regards,
Zia Mohammad
