### ISSUE TITLE
Additional Language Support

### ISSUE THREAD

**Issue by zmohammad01** [IBM/serverless-language-translation#30]
From my knowledge Watson LT supports multiple languages that are not reflected in the drop-down, perhaps these additional languages and support for them can be added?

For the languages not supported by STT/TTS (speech services) the mic/speaker can be disabled, but the language translation can still occur?

**Comment by kkbankol-ibm** [comment]
@ljbennett62, we've added those additional languages and indicated which languages have no audio support
