### ISSUE TITLE
mqttMsgReceived does not exist

### ISSUE THREAD

**Issue by markstur** [IBM/serverless-language-translation#31]
I went through this out-of-order while things were changing, but it looks to me like there's a step that requires mqttMsgReceived which does not exist (at least not yet).

bx wsk rule create handleMQTTMessage mqttMsgReceived translateText

error: Unable to create rule 'handleMQTTMessage': trigger /mark.sturdevant_myspace/mqttMsgReceived does not exist (code 03ac15c407bf50360aba72e460e6f7a6)

**Comment by kkbankol-ibm** [comment]
Hey Mark,

Thanks for pointing that out, the "mqttMsgReceived" trigger gets created as a result of deploying the MQTT feed, I've adjusted the order in #34 , would you mind seeing if that updated README looks good to you?

**Comment by kkbankol-ibm** [comment]
@ljbennett62 , this was due to an error in the ordering of the README steps, and has been addressed updating the README to direct the user to run the "Deploy MQTT Feed" step before creating the "Cloud Function" rules.
